services:
  - type: web
    name: mpesa-stk-qr-payment
    env: node
    region: oregon
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DARAJA_CONSUMER_KEY
        sync: false
      - key: DARAJA_CONSUMER_SECRET
        sync: false
      - key: DARAJA_PASSKEY
        sync: false
      - key: DARAJA_TILL_NUMBER
        sync: false
      - key: DARAJA_SHORTCODE
        sync: false
      - key: DARAJA_CALLBACK_URL
        sync: false
